/** Keep in sync with peakwa-sites/src/designs/catalog.ts names */
export const DESIGN_VARIANT_COUNT = 50;

export const DESIGN_CATALOG = [
  { id: 1, name: 'Classic Current', family: 'classic', description: 'Full-bleed left hero, 3-col services, multi-column footer' },
  { id: 2, name: 'Classic Bordered', family: 'classic', description: 'Left hero, bordered service cards, sharp corners' },
  { id: 3, name: 'Classic Soft Air', family: 'classic', description: 'Airy spacing, soft cards, light surface' },
  { id: 4, name: 'Classic Dark Band', family: 'classic', description: 'Dark trust band under hero, bold contrast' },
  { id: 5, name: 'Classic Center Stage', family: 'classic', description: 'Centered hero headline, balanced grid' },
  { id: 6, name: 'Classic Story Split', family: 'classic', description: 'About-forward layout with 2-col services' },
  { id: 7, name: 'Classic Icon Grid', family: 'classic', description: 'Soft icon cards, rounded CTAs' },
  { id: 8, name: 'Classic Alternating', family: 'classic', description: 'Alternating section bands, bordered cards' },
  { id: 9, name: 'Classic Phone Compact', family: 'classic', description: 'Phone-first header, compact hero' },
  { id: 10, name: 'Classic Footer Hub', family: 'classic', description: 'Rich multi-column footer focus, large service tiles' },
  { id: 11, name: 'Split Standard', family: 'split', description: '50/50 text-left image-right hero' },
  { id: 12, name: 'Split Reverse', family: 'split', description: 'Image left, text right, 2-col cards' },
  { id: 13, name: 'Split Float Card', family: 'split', description: 'Floating card hero energy, soft tiles' },
  { id: 14, name: 'Split Minimal Type', family: 'split', description: 'Minimal typography, list services, centered footer' },
  { id: 15, name: 'Split Asymmetric', family: 'split', description: 'Asymmetric hero, zigzag section rhythm' },
  { id: 16, name: 'Split Glass Soft', family: 'split', description: 'Glass-like soft cards, airy spacing' },
  { id: 17, name: 'Split Timeline', family: 'split', description: 'Icon-left services, process-forward flow' },
  { id: 18, name: 'Split Map Accent', family: 'split', description: 'Locations early, 3-col services' },
  { id: 19, name: 'Split Dual CTA', family: 'split', description: 'Phone-first + sticky call, bold bands' },
  { id: 20, name: 'Split Magazine', family: 'split', description: 'Magazine cover hero, mega service tiles' },
  { id: 21, name: 'Bold Overlay', family: 'bold', description: 'Dark overlay hero + accent action panel' },
  { id: 22, name: 'Bold Form Push', family: 'bold', description: 'Conversion stack with form-energy CTAs' },
  { id: 23, name: 'Bold Banner Strip', family: 'bold', description: 'Top urgency strip, sharp bordered cards' },
  { id: 24, name: 'Bold Center Stack', family: 'bold', description: 'Centered bold stack, mega tiles' },
  { id: 25, name: 'Bold Diagonal', family: 'bold', description: 'Diagonal band hero, sharp high contrast' },
  { id: 26, name: 'Bold Sticky Call', family: 'bold', description: 'Dense phone-first utility conversion' },
  { id: 27, name: 'Bold Proof First', family: 'bold', description: 'Reviews near top, then services' },
  { id: 28, name: 'Bold Mega Services', family: 'bold', description: 'Huge service tiles, left classic hero energy' },
  { id: 29, name: 'Bold Soft Dark', family: 'bold', description: 'Dark family with soft card islands' },
  { id: 30, name: 'Bold Checklist', family: 'bold', description: 'Checklist hero, icon-left services, sticky call' },
  { id: 31, name: 'Editorial Story', family: 'editorial', description: 'Centered story hero, cream paper surface' },
  { id: 32, name: 'Editorial Serif', family: 'editorial', description: 'Serif display, wide image under title' },
  { id: 33, name: 'Editorial Quote', family: 'editorial', description: 'Quote-led hero, proof-first flow' },
  { id: 34, name: 'Editorial Longform', family: 'editorial', description: 'Two-column story feel, list services' },
  { id: 35, name: 'Editorial Soft Grid', family: 'editorial', description: 'Muted soft grid, centered calm nav' },
  { id: 36, name: 'Editorial Team', family: 'editorial', description: 'Team/mission emphasis, icon services' },
  { id: 37, name: 'Editorial FAQ Lead', family: 'editorial', description: 'FAQ early, compact hero' },
  { id: 38, name: 'Editorial Local', family: 'editorial', description: 'Local storytelling, location early' },
  { id: 39, name: 'Editorial Polaroid', family: 'editorial', description: 'Image-led magazine cover, mega tiles' },
  { id: 40, name: 'Editorial Newsletter', family: 'editorial', description: 'Newsletter aesthetic, blog-forward calm' },
  { id: 41, name: 'Utility Phone First', family: 'utility', description: 'Phone strip + quick info dashboard' },
  { id: 42, name: 'Utility Table Rows', family: 'utility', description: 'Table-like service rows, sharp utility' },
  { id: 43, name: 'Utility Cards Desk', family: 'utility', description: 'Dashboard cards, compact density' },
  { id: 44, name: 'Utility Dense Split', family: 'utility', description: 'Dense split info, icon-left list' },
  { id: 45, name: 'Utility Emergency', family: 'utility', description: 'Urgent call-now overlay, list services' },
  { id: 46, name: 'Utility Segmented', family: 'utility', description: 'Segmented services feel, compact hero' },
  { id: 47, name: 'Utility Map Heavy', family: 'utility', description: 'Locations early, practical grid' },
  { id: 48, name: 'Utility FAQ Dense', family: 'utility', description: 'FAQ-forward dense utility layout' },
  { id: 49, name: 'Utility Mobile Stack', family: 'utility', description: 'Mobile-first stacked CTAs, soft cards' },
  { id: 50, name: 'Utility Hybrid Pro', family: 'utility', description: 'Hybrid: utility header + classic grid + bold end CTA' },
];
